[package]
name = "training_modpack"
version = "2.6.0"
authors = ["jugeeya <jugeeya@live.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
skyline = { git = "https://github.com/ultimate-research/skyline-rs.git" }
skyline_smash = { git = "https://github.com/ultimate-research/skyline-smash.git" }
skyline-web = { git = "https://github.com/skyline-rs/skyline-web.git" }
bitflags = "1.2.1"
parking_lot = { version = "0.11.0", features = ["nightly"] }
lazy_static = "1.4.0"
owo-colors = "1.1.3"
ramhorns = "0.10.1"
paste = "1.0"
num = "0.3.0"
num-derive = "0.3"
num-traits = "0.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true

[package.metadata.skyline]
titleid = "01006A800016E000"
plugin-dependencies = [
    { name = "libnro_hook.nro", url = "https://github.com/ultimate-research/nro-hook-plugin/releases/download/v0.1.1/libnro_hook.nro" },
    { name = "libparam_hook.nro", url = "https://github.com/ultimate-research/params-hook-plugin/releases/download/v0.1.1/libparam_hook.nro" },
]

